//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Terminal.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Queue.Terminal.Translation.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно {0}.
        /// </summary>
        internal static string AvailableCount {
            get {
                return ResourceManager.GetString("AvailableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено администратором.
        /// </summary>
        internal static string DisabledByAdmin {
            get {
                return ResourceManager.GetString("DisabledByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата предварительной записи не выбрана.
        /// </summary>
        internal static string EarlyDateNotSelected {
            get {
                return ResourceManager.GetString("EarlyDateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время предварительной записи не выбрано.
        /// </summary>
        internal static string EarlyTimeNotSelected {
            get {
                return ResourceManager.GetString("EarlyTimeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет свободного времени.
        /// </summary>
        internal static string NoFreeTime {
            get {
                return ResourceManager.GetString("NoFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пожалуйста ФИО.
        /// </summary>
        internal static string NoNameWarn {
            get {
                return ResourceManager.GetString("NoNameWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данную услугу невозможно записаться через терминал. Обратитесь к администратору.
        /// </summary>
        internal static string ServiceNotAvailableOnTerminal {
            get {
                return ResourceManager.GetString("ServiceNotAvailableOnTerminal", resourceCulture);
            }
        }
    }
}
