; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Junte Queue Server"
!define EXE_NAME "Queue.Hosts.Server.WinService.exe"
!define PRODUCT_VERSION "1.0.0.0"
!define PRODUCT_PUBLISHER "Junte"
!define PRODUCT_WEB_SITE "http://junte.ru/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\${EXE_NAME}"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Russian"

; MUI end ------

RequestExecutionLevel admin

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup_${PRODUCT_VERSION}.exe"
InstallDir "$PROGRAMFILES32\${PRODUCT_PUBLISHER}\${PRODUCT_NAME}"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "CopyFiles"
  SetShellVarContext all
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  SetOverwrite try

  File "${EXE_NAME}"
  File "${EXE_NAME}.config"
  File "AutoMapper.dll"
  File "AutoMapper.Net4.dll"
  File "FluentNHibernate.dll"
  File "ICSharpCode.SharpZipLib.dll"
  File "Iesi.Collections.dll"
  File "Junte.Data.Common.dll"
  File "Junte.Data.NHibernate.dll"
  File "Junte.Parallel.Common.dll"
  File "Junte.WCF.Common.dll"
  File "log4net.dll"
  File "Microsoft.Practices.ServiceLocation.dll"
  File "Microsoft.Practices.Unity.dll"
  File "NHibernate.Caches.SysCache2.dll"
  File "NHibernate.dll"
  File "NHibernate.Mapping.Attributes.dll"
  File "NHibernate.Validator.dll"
  File "NPOI.dll"
  File "Queue.Common.dll"
  File "Queue.Model.Common.dll"
  File "Queue.Model.dll"
  File "Queue.Reports.dll"
  File "Queue.Server.dll"
  File "Queue.Services.Common.dll"
  File "Queue.Services.Contracts.dll"
  File "Queue.Services.DTO.dll"
  File "Queue.Services.Server.dll"
SectionEnd

Section -InstallService
  DetailPrint "Установка сервиса..."

  ExecWait 'sc create "${PRODUCT_NAME}" binPath= "$INSTDIR\${EXE_NAME}" DisplayName= "${PRODUCT_NAME}" start= auto' $0
  ${If} $0 != 0
    DetailPrint "Сервис не установлен."
    MessageBox MB_ICONINFORMATION|MB_OK "Не удалось установить сервис"
    Abort
  ${EndIf}

  DetailPrint "Сервис успешно установлен"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

Section -RunService
  ExecWait 'sc start "${PRODUCT_NAME}"' $0
  ${If} $0 != 0
    DetailPrint "Не удалось запустить сервис"
    MessageBox MB_ICONINFORMATION|MB_OK "Не удалось установить службу. Ошибка: $0"
  ${EndIf}
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "Удаление программы $(^Name) было успешно завершено."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Вы уверены в том, что желаете удалить $(^Name) и все компоненты программы?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ExecWait 'sc stop "${PRODUCT_NAME}"'
  ExecWait 'sc delete "${PRODUCT_NAME}"'

  Delete "$INSTDIR\${EXE_NAME}.config"
  Delete "$INSTDIR\${EXE_NAME}"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\Queue.Services.Server.dll"
  Delete "$INSTDIR\Queue.Services.DTO.dll"
  Delete "$INSTDIR\Queue.Services.Contracts.dll"
  Delete "$INSTDIR\Queue.Services.Common.dll"
  Delete "$INSTDIR\Queue.Server.dll"
  Delete "$INSTDIR\Queue.Reports.dll"
  Delete "$INSTDIR\Queue.Model.dll"
  Delete "$INSTDIR\Queue.Model.Common.dll"
  Delete "$INSTDIR\Queue.Common.dll"
  Delete "$INSTDIR\NPOI.dll"
  Delete "$INSTDIR\NHibernate.Validator.dll"
  Delete "$INSTDIR\NHibernate.Mapping.Attributes.dll"
  Delete "$INSTDIR\NHibernate.dll"
  Delete "$INSTDIR\NHibernate.Caches.SysCache2.dll"
  Delete "$INSTDIR\Microsoft.Practices.Unity.dll"
  Delete "$INSTDIR\Microsoft.Practices.ServiceLocation.dll"
  Delete "$INSTDIR\log4net.dll"
  Delete "$INSTDIR\Junte.WCF.Common.dll"
  Delete "$INSTDIR\Junte.Parallel.Common.dll"
  Delete "$INSTDIR\Junte.Data.NHibernate.dll"
  Delete "$INSTDIR\Junte.Data.Common.dll"
  Delete "$INSTDIR\Iesi.Collections.dll"
  Delete "$INSTDIR\ICSharpCode.SharpZipLib.dll"
  Delete "$INSTDIR\FluentNHibernate.dll"
  Delete "$INSTDIR\AutoMapper.Net4.dll"
  Delete "$INSTDIR\AutoMapper.dll"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd