//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Queue.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Grid xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///      xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///      xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///      xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///      Width=&quot;280&quot;
        ///      Background=&quot;#FFFFFF&quot;
        ///      mc:Ignorable=&quot;d&quot;&gt;
        ///    &lt;Grid.Resources&gt;
        ///        &lt;Style x:Key=&quot;{x:Type GroupBox}&quot; TargetType=&quot;{x:Type GroupBox}&quot;&gt;
        ///            &lt;Setter Property=&quot;BorderThickness&quot; Value=&quot;2&quot; /&gt;
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ClientRequestCoupon {
            get {
                return ResourceManager.GetString("ClientRequestCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p id=&apos;copyright&apos;&gt;Система электронной очереди Junte 2007-2013&lt;a href=&apos;http://www.junte.ru/queue&apos; target=&apos;_blank&apos; class=&apos;btn btn-mini&apos; type=&apos;button&apos;&gt;junte.ru&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string PortalFooter {
            get {
                return ResourceManager.GetString("PortalFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;Добро пожаловать к нам!&lt;/p&gt;
        ///&lt;p&gt;Запишитесь на прием в нашу организацию в режиме онлайн!&lt;/p&gt;&lt;hr /&gt;
        ///&lt;p&gt;&lt;a href=&apos;/client/&apos; class=&apos;btn btn-primary btn-large&apos;&gt;Каталог услуг &lt;i class=&apos;icon-arrow-right icon-white&apos;&gt;&lt;/i&gt;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string PortalHeader {
            get {
                return ResourceManager.GetString("PortalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Border xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;&gt;
        ///    &lt;Grid&gt;
        ///        &lt;Grid&gt;
        ///            &lt;Grid.RowDefinitions&gt;
        ///                &lt;RowDefinition Height=&quot;auto&quot; /&gt;
        ///                &lt;RowDefinition Height=&quot;auto&quot; /&gt;
        ///                &lt;RowDefinition /&gt;
        ///            &lt;/Grid.RowDefi [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TerminalWindow {
            get {
                return ResourceManager.GetString("TerminalWindow", resourceCulture);
            }
        }
    }
}
