//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Queue.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///      xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///      xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///      xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///      Width=&quot;280&quot;
        ///      Background=&quot;#FFFFFF&quot;
        ///      mc:Ignorable=&quot;d&quot;&gt;
        ///    &lt;Grid.Resources&gt;
        ///        &lt;Style x:Key=&quot;{x:Type GroupBox}&quot; TargetType=&quot;{x:Type GroupBox}&quot;&gt;
        ///            &lt;Setter Property=&quot;BorderThickness&quot; Value=&quot;2&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClientRequestCoupon {
            get {
                return ResourceManager.GetString("ClientRequestCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p id=&apos;copyright&apos;&gt;Система электронной очереди Junte 2007-2013&lt;a href=&apos;http://www.junte.ru/queue&apos; target=&apos;_blank&apos; class=&apos;btn btn-mini&apos; type=&apos;button&apos;&gt;junte.ru&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string PortalFooter {
            get {
                return ResourceManager.GetString("PortalFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Добро пожаловать к нам!&lt;/p&gt;
        ///&lt;p&gt;Запишитесь на прием в нашу организацию в режиме онлайн!&lt;/p&gt;&lt;hr /&gt;
        ///&lt;p&gt;&lt;a href=&apos;/client/&apos; class=&apos;btn btn-primary btn-large&apos;&gt;Каталог услуг &lt;i class=&apos;icon-arrow-right icon-white&apos;&gt;&lt;/i&gt;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string PortalHeader {
            get {
                return ResourceManager.GetString("PortalHeader", resourceCulture);
            }
        }
    }
}
