//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scheme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scheme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Queue.Database.Scheme", typeof(Scheme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select true;.
        /// </summary>
        internal static string _001 {
            get {
                return ResourceManager.GetString("_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _config_media set TickerSpeed = 5;.
        /// </summary>
        internal static string _002 {
            get {
                return ResourceManager.GetString("_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _client_request set WaitingStartTime = RequestTime;.
        /// </summary>
        internal static string _003 {
            get {
                return ResourceManager.GetString("_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _user set Role = &apos;Administrator&apos; where Role = &apos;Manager&apos;;.
        /// </summary>
        internal static string _004 {
            get {
                return ResourceManager.GetString("_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _user set [Permissions] = 511 where Role  = &apos;Administrator&apos;;.
        /// </summary>
        internal static string _005 {
            get {
                return ResourceManager.GetString("_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table _service drop column Type;.
        /// </summary>
        internal static string _006 {
            get {
                return ResourceManager.GetString("_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _user set IsActive = 1;.
        /// </summary>
        internal static string _007 {
            get {
                return ResourceManager.GetString("_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _schedule set LiveClientInterval = ClientInterval, EarlyClientInterval = ClientInterval;.
        /// </summary>
        internal static string _008 {
            get {
                return ResourceManager.GetString("_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table _schedule drop column ClientInterval;.
        /// </summary>
        internal static string _009 {
            get {
                return ResourceManager.GetString("_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table _schedule drop column IsInterruption;.
        /// </summary>
        internal static string _010 {
            get {
                return ResourceManager.GetString("_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table _schedule drop column InterruptionStartTime;.
        /// </summary>
        internal static string _011 {
            get {
                return ResourceManager.GetString("_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table _schedule drop column InterruptionFinishTime;.
        /// </summary>
        internal static string _012 {
            get {
                return ResourceManager.GetString("_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _workplace set DisplayDeviceId = Display;.
        /// </summary>
        internal static string _013 {
            get {
                return ResourceManager.GetString("_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table _workplace drop column Display;.
        /// </summary>
        internal static string _014 {
            get {
                return ResourceManager.GetString("_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _service_group set FontSize = 1;.
        /// </summary>
        internal static string _015 {
            get {
                return ResourceManager.GetString("_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update _service set FontSize = 1;.
        /// </summary>
        internal static string _016 {
            get {
                return ResourceManager.GetString("_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE _client_request DROP CONSTRAINT ClientRequestToClientReference;
        ///-- SEPARATOR
        ///ALTER TABLE _client_request ADD CONSTRAINT ClientRequestToClientReference FOREIGN KEY(ClientId)
        ///REFERENCES _client (Id)
        ///ON DELETE CASCADE;
        ///-- SEPARATOR
        ///ALTER TABLE _client_request DROP CONSTRAINT ClientRequestToOperatorReference;
        ///-- SEPARATOR
        ///ALTER TABLE _client_request ADD CONSTRAINT ClientRequestToOperatorReference FOREIGN KEY(OperatorId)
        ///REFERENCES _user (Id)
        ///ON DELETE SET NULL;
        ///-- SEPARATOR
        ///ALTER TABLE _ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string constraints {
            get {
                return ResourceManager.GetString("constraints", resourceCulture);
            }
        }
    }
}
