//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queue.Model.Common.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkplaceModificator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkplaceModificator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Queue.Model.Common.Translate.WorkplaceModificator", typeof(WorkplaceModificator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а.
        /// </summary>
        public static string CHAR1 {
            get {
                return ResourceManager.GetString("CHAR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to б.
        /// </summary>
        public static string CHAR2 {
            get {
                return ResourceManager.GetString("CHAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в.
        /// </summary>
        public static string CHAR3 {
            get {
                return ResourceManager.GetString("CHAR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г.
        /// </summary>
        public static string CHAR4 {
            get {
                return ResourceManager.GetString("CHAR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д.
        /// </summary>
        public static string CHAR5 {
            get {
                return ResourceManager.GetString("CHAR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е.
        /// </summary>
        public static string CHAR6 {
            get {
                return ResourceManager.GetString("CHAR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ж.
        /// </summary>
        public static string CHAR7 {
            get {
                return ResourceManager.GetString("CHAR7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to з.
        /// </summary>
        public static string CHAR8 {
            get {
                return ResourceManager.GetString("CHAR8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
    }
}
